<script>
    require([
        'jquery',
        'owlcarousel'
    ], function () {
        'use strict';
        jQuery.noConflict();
        jQuery(".owl-carousel").owlCarousel({
            //nav: true, // Show next and prev buttons
            //navText:["previous","next"], //show prev next
            loop: true,
            autoplay: true, //Set AutoPlay
            autoplayHoverPause: true, //stop when mouse on carousel
            items : 1
        });
    });
</script>

<div class="owl-carousel owl-theme">
    <div class="slide-one div1"><h1  class="text-center div2">Slide 1</h1></div>
    <div class="slide-two div1"><h1  class="text-center div2">Slide 2</h1></div>
    <div class="slide-three div1"><h1  class="text-center div2">Slide 3</h1></div>
</div>