
   <!--  <?php
    $array_key = $block->grabbingData(); 
    //echo __('Model Saved With Entity ID %1',$block->getTestModel()->getData('test_id')); 
    //print_r( $array_key);
    //print_r($block->getTestModel()->getData());

    
    ?>



<div>
    <table class="data table text-center" >
        <thead>
            <th scope="col" class="col text-center">User E-mail</th>
            <th scope="col" class="col text-center">Login-time</th>
            <th scope="col" class="col text-center">Logout-time</th>
        </thead>
            <?php 
                foreach($array_key as $row)
                {
                    ?>
                    <tr>
                        <td scope="col" class="col">
                            <?php echo $row['email']; ?>
                        </td>
                        <td scope="col" class="col">
                            <?php echo $row['login_time']; ?>
                        </td>
                        <td scope="col" class="col">
                            <?php echo $row['logout_time']; ?>
                        </td>
                    </tr>
                    <?php
                }
            ?>
        <tbody>
            
                
            
        </tbody>
    </table>
</div> -->
<div data-bind="scope: 'koexample'">
<!-- ko template: getTemplate() --><!-- /ko -->
</div>
  
<script type="text/x-magento-init">
        {
            "*": {
                "Magento_Ui/js/core/app": {
                    "components": {
                        "koexample": {
                            "component": "Excellence_Hello/js/knock",
                            "template" : "Excellence_Hello/example"
                        }
                    }
                }
            }
        }
</script>ss