<div class="row">
    <div class="column-3">
         <span style="font-family:'Oswald'; font-weight:500;">CUSTOMER SERVICES</span>
         <span style="font-family:'Oswald';">
            <br/>
            <a style="text-decoration:none; color:gray;" href="#">FAQ</a><br/>
            <a style="text-decoration:none; color:gray;" href="#">ORDER STATUS</a><br/>
            <a style="text-decoration:none; color:gray;" href="#">SHIPPING INFORMATION</a><br/>
            <a style="text-decoration:none; color:gray;" href="#">RETURN EXCHANGES</a><br/>
            <a style="text-decoration:none; color:gray;" href="#">SIZE CHART</a><br/>
            <a style="text-decoration:none; color:gray;" href="#">CONTACT US</a></br>
         </span>
    </div>
    <div class="column-3">
    <span style="font-family:'Oswald'; font-weight:500;">RUDSAK</span>
         <span style="font-family:'Oswald';">
            <br/>
            <a style="text-decoration:none; color:gray;" href="#">ABOUT US</a><br/>
            <a style="text-decoration:none; color:gray;" href="#">STORE LOCATOR</a><br/>
            <a style="text-decoration:none; color:gray;" href="#">GIFT CARDS</a><br/>
            <a style="text-decoration:none; color:gray;" href="#">CAREER</a><br/>
            <a style="text-decoration:none; color:gray;" href="#">WHOLESALES</a><br/>
            <a style="text-decoration:none; color:gray;" href="#">PRESS INQUIRIES</a></br>
            <a style="text-decoration:none; color:gray;" href="#">CORPORATE GIFTING</a></br>
         </span>        
    </div>
    <div class="column-3">
        <span style="font-family:'Oswald'; font-weight:500;">CONNECT WITH US</span>
        <br/><br/>
        <a href="#"><img class="footer-padding" src="<?php echo $this->getViewFileUrl("images/facebook.png"); ?>" /></a>
        <a href="#"><img class="footer-padding" src="<?php echo $this->getViewFileUrl("images/tumbler.png"); ?>" /></a>
        <a href="#"><img class="footer-padding" src="<?php echo $this->getViewFileUrl("images/pintrest.png"); ?>" /></a>
        <a href="#"><img class="footer-padding" src="<?php echo $this->getViewFileUrl("images/instagram.png"); ?>" /></a>
        <a href="#"><img class="footer-padding" src="<?php echo $this->getViewFileUrl("images/youtube.png"); ?>" /></a>
    </div>
</div>