<?php
/**
 * Copyright © Magento, Inc. All rights reserved.
 * See COPYING.txt for license details.
 */

// @codingStandardsIgnoreFile

/** @var \Magento\Customer\Block\Account\AuthorizationLink $block */

$dataPostParam = '';
if ($block->isLoggedIn()) {
    $dataPostParam = sprintf(" data-post='%s'", $block->getPostParams());
}
?>
<li class="authorization-link" data-label="<?= $block->escapeHtml(__('or')) ?>">
    <a <?= /* @noEscape */ $block->getLinkAttributes() ?><?= /* @noEscape */ $dataPostParam ?>>
      <span style=""><img style="height:14px;" src="<?php echo $block->getUrl("pub/media/images")?>user.png" alit="slide1" alt="user-logo" /></span>
      <span style="font-size:12px; vertical-align: text-top;">SIGN IN/REGISTER</span>
    </a>
</li>
