<?php
// $test = $block->grabbingProductList();
// //echo get_class($block);
// echo "<pre>";
// // print_r($test);
?>



<div class="row">
    <div class="column-3">
        <img src="<?php echo $block->getUrl("pub/media/images")?>leaf.png"  alt="100%-canadian-design"/><br/>
        <img src="<?php echo $block->getUrl("pub/media/images")?>100.png"  alt="100%-canadian-design"/>
    </div>
    <div class="column-3">
        <img src="<?php echo $block->getUrl("pub/media/images")?>shield.png"  alt="shield"/><br/>
        <img src="<?php echo $block->getUrl("pub/media/images")?>established.png"  alt="established"/>
    </div>
    <div class="column-3">
        <img src="<?php echo $block->getUrl("pub/media/images")?>snap.png"  alt="snap"/><br/>
        <img src="<?php echo $block->getUrl("pub/media/images")?>genuine.png"  alt="genuine"/>
    </div>
</div>



<div>
    <div class="column-2 back-img">
            <img class="full-width" src="<?php echo $block->getUrl("pub/media/images")?>shot1.png"  alt="100%-canadian-design"/><br/>
            <div class="centered">
                <img src="<?php echo $block->getUrl("pub/media/images")?>up-to-30.png"  alt="up-to-30"/><br/>
            </div>
    </div>

    <div class="column-2 back-img">
        <img class="full-width" src="<?php echo $block->getUrl("pub/media/images")?>handbags.png"  alt="hand-bags"/><br/>
        <div class="centered">
            <img src="<?php echo $block->getUrl("pub/media/images")?>because.png"  alt="up-to-30"/><br/>
            <img src="<?php echo $block->getUrl("pub/media/images")?>celebrate.png"  alt="up-to-30"/><br/>
        </div>
    </div>

</div>


<!-- above link set pending -->
<div>
    <div class="column-2" style="text-align:left;">
        <img src="<?php echo $this->getViewFileUrl("images/black-women.png"); ?>"  alt="up-to-30"/>
    </div>

    <div class="column-2 women-catalog-slider">
        <div class="catalog-text">
            <img src="<?php echo $this->getViewFileUrl("images/femmes.png"); ?>" alit="slide1"  /><br/>
            <img style="padding-top: 4%;" src="<?php echo $this->getViewFileUrl("images/lora-ipsum.png"); ?>" alit="slide1"  />
        </div>

        <div class="owl-carousel catalog-carousel owl-theme">
            <div class="item text-center"><img src="<?php echo $this->getViewFileUrl("images/s-1.png"); ?>" alit="slide1" /><br/>
                    <span class="demand-font">MEDINA<br/>$79.99</span>
            </div>
            <div class="item text-center" ><img src="<?php echo $this->getViewFileUrl("images/s-2.png"); ?>" alit="slide1" /><br/>
                    <span class="demand-font">MARIBEL<br/>$119.99</span>
            </div>
            
        </div>
    </div>
</div>






<div style="width:100%; float:left;" >
    

    <div class="column-2 men-catalog-slider">
        <div class="catalog-text">
            <img src="<?php echo $this->getViewFileUrl("images/hommes.png"); ?>" alit="slide1"  /><br/>
            <img style="padding-top: 4%;" src="<?php echo $this->getViewFileUrl("images/lora-ipsum.png"); ?>" alit="slide1"  />
        </div>

        <div class="owl-carousel catalog-carousel owl-theme">
            <div class="item text-center"><img src="<?php echo $this->getViewFileUrl("images/men-1.png"); ?>" alit="slide1" /><br/>
                    <span class="demand-font">MEDINA<br/>$79.99</span>
            </div>
            <div class="item text-center" ><img src="<?php echo $this->getViewFileUrl("images/men-2.png"); ?>" alit="slide1" /><br/>
                    <span class="demand-font">MARIBEL<br/>$119.99</span>
            </div>
            
        </div>
    </div>

    <div class="column-2">
        <img src="<?php echo $this->getViewFileUrl("images/men-black-white.png"); ?>"  alt="up-to-30"/>
    </div>
</div>



<!-- less essential slider -->
<div class="less-essential">
    <div class="less-text">
        <img src="<?php echo $this->getViewFileUrl("images/less-essential.png"); ?>" alit="slide1" />
    </div>

    <div style="width:100%;">
        <div class="owl-carousel less-essential-slider owl-theme">
            <div class="item text-center"><img src="<?php echo $this->getViewFileUrl("images/men-1.png"); ?>" alit="slide1" /><br/>
                    <span class="demand-font">MEDINA<br/>$79.99</span>
            </div>
            <div class="item text-center" ><img src="<?php echo $this->getViewFileUrl("images/men-2.png"); ?>" alit="slide1" /><br/>
                    <span class="demand-font">MARIBEL<br/>$119.99</span>
            </div>
            <div class="item text-center"><img src="<?php echo $this->getViewFileUrl("images/men-1.png"); ?>" alit="slide1" /><br/>
                    <span class="demand-font">MEDINA<br/>$79.99</span>
            </div>
            <div class="item text-center" ><img src="<?php echo $this->getViewFileUrl("images/men-2.png"); ?>" alit="slide1" /><br/>
                    <span class="demand-font">MARIBEL<br/>$119.99</span>
            </div>
            <div class="item text-center"><img src="<?php echo $this->getViewFileUrl("images/men-2.png"); ?>" alit="slide1" /><br/>
                    <span class="demand-font">MEDINA<br/>$79.99</span>
            </div>
            
        </div>
    </div>
</div>







<script>
    require([
        'jquery',
        'owlcarousel'
    ], function ($) {
        // 'use strict';
        // $.noConflict();

        //less-essential-slider
        $(".less-essential-slider").owlCarousel({
            loop:true,
            margin:10,
            nav:true,
            items: 5,
            responsive:{
                0:{
                    items:1
                },
                600:{
                    items:2
                },
                1000:{
                    items:5
                }
            }
        });


        //men-catalog-carousel
        $(".men-catalog-carousel").owlCarousel({
            loop:true,
            margin:10,
            nav:true,
            dots: true,
            items: 2,
            dots:true,
            dotsData:true,
            responsive:{
                0:{
                    items:1
                },
                600:{
                    items:2
                },
                1000:{
                    items:2
                }
            }
        });

        //women-catalog-slider

        $(".catalog-carousel").owlCarousel({
            loop:true,
            margin:10,
            nav:true,
            items: 2,
            dots:true,
            dotsData:true,
            responsive:{
                0:{
                    items:1
                },
                600:{
                    items:2
                },
                1000:{
                    items:2
                }
            }
        });


        
    });
</script>