<script type="text/javascript">
    require([
        'jquery',
        'owlCarousel'
    ], function($,owlCarousel){
        $('.owl-carousel').owlCarousel({
            item : 1,
            lazyLoad :true,
            loop :true,
            margin :10
        });
    });
</script>


<div class="owl-carousel owl-theme">
    <div><img src="https://placehold.it/350x250&text=1"></div>
    <div><img src="https://placehold.it/350x250&text=2"></div>
    <div><img src="https://placehold.it/350x250&text=3"></div>
</div>