<script>
    require([
        'jquery',
        'owlcarousel'
    ], function () {
        'use strict';
        jQuery.noConflict();
        jQuery(".owl-carousel").owlCarousel({
            //nav: true, // Show next and prev buttons
            //navText:["previous","next"], //show prev next
            loop: true,
            autoplay: true, //Set AutoPlay
            autoplayHoverPause: true, //stop when mouse on carousel
            items : 1
        });
    });
</script>

<div class="owl-carousel owl-theme">
    <div><img src="<?php echo $block->getUrl("pub/media/images")?>slide1.png" alit="slide1" /></div>
    <div><img src="<?php echo $block->getUrl("pub/media/images")?>slide1.png" alit="slide2" /></div>
    <div><img src="<?php echo $block->getUrl("pub/media/images")?>slide1.png" alit="slide3" /></div>
</div>
