<?php
/**
 * Copyright © Magento, Inc. All rights reserved.
 * See COPYING.txt for license details.
 */

// @codingStandardsIgnoreFile

/** @var \Magento\Newsletter\Block\Subscribe $block */

?>
<div class="block newsletter">
    <div class="title"><strong><?= $block->escapeHtml(__('Newsletter')) ?></strong></div>
    <div class="content">
    
        <form class="form subscribe"
            novalidate
            action="<?= $block->escapeUrl($block->getFormActionUrl()) ?>"
            method="post"
            data-mage-init='{"validation": {"errorClass": "mage-error"}}'
            id="newsletter-validate-detail">
            <div class="newsletter-text">
                STAY CONNECTED
            </div>
            <div class="field newsletter" style="float:right;     width: 50%;">
                <label class="label" for="newsletter"><span><?= $block->escapeHtml(__('Sign Up for Our Newsletter:')) ?></span></label>
                
                <div>
                 <input name="email"style="border:none; border-bottom:1px solid gray; background:transparent; color:#fff; font-family:'Oswald';" type="email" id="newsletter"
                                placeholder="<?= $block->escapeHtml(__('Enter your email address')) ?>"
                                data-validate="{required:true, 'validate-email':true}"/>
                </div>
            </div>
            <div class="actions" style="padding: 0 8px 0 16px;"">
                <button style="color: #000;
    border: 1px solid #fff;
    background: #fff;" class="action subscribe primary" title="<?= $block->escapeHtmlAttr(__('Subscribe')) ?>" type="submit">
                    <span><?= $block->escapeHtml(__('WOMEN')) ?></span>
                </button>
            </div>
            <div class="actions">
                <button style="color: #000;
    border: 1px solid #fff;
    background: #fff;" class="action subscribe primary" title="<?= $block->escapeHtmlAttr(__('Subscribe')) ?>" type="submit">
                    <span style="padding:10px;"><?= $block->escapeHtml(__('MEN')) ?></span>
                </button>
            </div>
        </form>
    </div>
</div>



